// mgmp_unlocks.h -- the unlock flags that shape the chapter map, and what every player has.
//
// The chapter map is generated by each peer from its OWN save: the nodes of the hard path, the sewers and junkyard exits, the later chapters'
// exits are locked or open by the `mapflag_*` properties (data/maps/*.gon, `flags { ... }`), so two players with different progress generated
// different maps and the first node boundary refused to certify them ("map state differs between participants"). The rule now: the map is
// generated from the flags EVERY player has -- the least progress decides, and the host cannot enter a node a player could not.
//
// How: each client reports its flags in its READY, the host ANDs them with its own and sends the result with the chapter command, and while
// the map is being generated (from the commit until the first live map tick) the save-properties getter answers `mapflag_*` from that set on
// every peer. The chapter choice follows the same flags: chapter 2 needs DesertUnlocked, chapter 3 also LabUnlocked.
#pragma once

#include <cstdint>

namespace mgmp {

// The fixed order of the flag set on the wire (bit n = flag n). Never reorder; append only (and bump the protocol).
constexpr uint32_t kMapFlag_Desert = 1u << 8;    // mapflag_DesertUnlocked -- chapter 2 may be chosen
constexpr uint32_t kMapFlag_Lab    = 1u << 18;   // mapflag_LabUnlocked    -- the three-chapter page

// THIS player's flags, read live from the running game. All bits when the game's debug unlock-everything byte is set, and all bits when
// nothing can be read: an unreadable state must never lock anybody out (and is neutral in the AND).
uint32_t unlocks_mapflags();

// Whether a flag set lets its player choose chapter `act` (1..3). Chapter 3 needs chapter 2 as well.
inline bool unlocks_allow(uint32_t flags, int act) {
    if (act <= 1) return true;
    if (!(flags & kMapFlag_Desert)) return false;
    return act == 2 || (flags & kMapFlag_Lab) != 0;
}

// From now on (until unlocks_override_clear, or a minute) the save-properties getter answers mapflag_* from `flags` instead of the save.
void unlocks_override_set(uint32_t flags);
void unlocks_override_clear();
bool unlocks_override_active();
// The property-getter detour's question, for `key` whose own answer was `local`: true with the value to return when the key is one an override answers --
// a mapflag_* while a chapter map is generated, or one of the properties the random events read while a client follows the host through an event.
bool unlocks_override_lookup(const char* key, int64_t local, int64_t& value);

// ---- THE HOST'S UNLOCK LISTS DECIDE HOW A BATTLE IS BUILT --------------------------------------------------------------------------------------
//
// A battle is generated from the local save's unlock state: which level groups a level may come from, which pickups the loot table rolls, which abilities
// and passives the spawn tables may hand out. Two players with different progress built different battles (36 units here, 38 there, other starting tiles)
// and the first turn hash refused. So while a CLIENT is in a battle or event node -- from the moment it follows the host in until the map is ready again
// (the whole battle and its rewards: a mid-battle roll from an unlocked pool must not differ either) -- the "is X unlocked" checks and the save
// properties the events read answer with the HOST's answers. Outside it (chests, shops, the map) everybody keeps their own.
// The host sends one bit per name of the game's blacklists (mgmp_unlock_lists.h) before it enters a battle node; a name that is not on a blacklist is
// available to everybody and is never touched.
enum class UnlockList : uint8_t { Ability, Passive, Item, LevelGroup, Boss };
struct UnlocksMsg;
// Host: read this game's own answers and send them to the clients (a no-op without a session).
void unlocks_publish();
// Client: the host's answers arrived.
void unlocks_on_message(uint8_t from, const UnlocksMsg& m);
// Client: a battle or event node is being entered (`why` is for the log). The window ends when the map is ready again (unlocks_on_map) or after 3 h.
void unlocks_window_open(const char* why, bool event = false);
// Client, every map update: whether the map is ready. The window closes on the first ready map after the client has left it (a not-ready map, or a
// battle that was built, counts as having left).
void unlocks_on_map(bool ready);
void unlocks_window_close(const char* why);
bool unlocks_window_active();
// The class-list function ran (both peers, from its hook): record this peer's list and, on a client in a battle's window, replace it by the host's. See mgmp_unlocks.cpp.
void unlocks_classes_after(void* out_vector, bool with_colorless);
// A level-up screen is about to be built (its constructor builds the option pool, the unlock queries of which come BEFORE any log line of ours): if this is the reward of a fight, the fight is over -- both the
// per-name unlock answers and the class list answer with this save's own from here on. A normal win leaves objects and summons standing, so "every enemy is down" alone is not seen.
void unlocks_level_screen_opens();
// THE UNLOCK-QUERY RECORD (both peers, every battle): see mgmp_unlocks.cpp. `local` is what this save says, `answer` what the game was told.
void unlockq_query(UnlockList list, const char* name, bool local, bool answer);
void unlockq_prop(const char* key, int64_t local, int64_t answer);
void unlockq_flush(uint32_t turn, uint32_t actions_done);     // one UQ line for the queries since the last one; the digest also goes to the other peers (MSG_UQD)
struct UqdMsg;
void unlockq_on_peer(uint8_t from, const UqdMsg& m);          // another peer's digest of the same flush: compared with this peer's
void unlockq_stats(uint32_t& compared, uint32_t& mismatched);  // this battle's comparisons, for the summary line
struct PropsMsg;
void unlocks_props_on_message(uint8_t from, const PropsMsg& m);  // a chunk of the host's save-property table (client)
// Every frame: notes that the battle has been built (the window then stays open until the map is ready again).
void unlocks_tick();
// The detours' answer for a check made inside the window: `local` is what this save said. Returns the HOST's answer for a name on a blacklist, and `local`
// for everything else (and when no snapshot has arrived). Every answer that differs from this save's is logged.
bool unlocks_window_answer(UnlockList list, const char* name, bool local);

// The battle's party sort (sub_140364760), called by its hook before (sorted = false) and after the game sorts: both peers log the order and
// every party cat's stats with the inputs they come from; then every peer puts the party into one canonical order -- speed, highest first,
// ties by the party list (the game breaks them with a shuffle of the shared stream). Only in a room.
void unlocks_spawn_sort(void** first, void** last, bool sorted);

// The battle build is starting (T_BattleBuild): in a room the shared stream is set from the battle id, the same on every peer -- the draws
// made between the node entry and here differ per save (measured 2026-10-02), and the board is placed from this stream.
// One player cat as text and a fingerprint of that text (the stats, every input they come from, class, abilities, gear): what the pre-battle audit compares.
bool unlocks_describe_cat(void* catdata, uint64_t& id, char* text, size_t cap, uint64_t& fp);
void unlocks_battle_build();
// The battle build has returned / a definition is being loaded: inside the build every load starts from a stream derived from the battle id and the
// load's number, so a draw that differs inside one load (per-save state) cannot move the loads after it. Only in a room.
void unlocks_battle_build_done();
void unlocks_build_load();
// The same, when the definition load has returned, and at the end of each build stage: the shared stream is set from the battle id, so a draw count
// that differs between saves (a random cat's name ...) cannot reach the bird roll, the pickup counts or the first turn.
void unlocks_build_load_done();
// THE SAME FENCE FOR A DEFINITION LOADED MID-BATTLE (a summon, a pickup, a returning enemy) -- see the definitions. No-ops outside a fight of a room with two or more peers, and while the
// battle build's own fence is up. The _done must be called after every _load, whatever it returned.
void unlocks_midbattle_load(const char* what);
void unlocks_midbattle_load_done();
void unlocks_build_stage_end(const char* stage);
// Start of the battle build's enemy stage (0x35D0B0), before the original runs: both peers log the director's queue of returning enemies; a client
// aligns its queue with the host's (the host sent it with the level).
void unlocks_build_enemies_begin();
// An event outcome is about to draw from a `random_pool` (T_RandomPool): in a room the shared stream is set from the node's seed and the number of draws made on this
// node, so both peers pick -- and roll the entry's own numbers -- from the same state.
void unlocks_event_roll();
// The call that picks an event's SUBJECT cat (`cat_choice random` ...): `vec` = the candidate vector (count at +4, element pointers at +8), `pick` = the game's own "random element"
// helper. In a room the candidates are sorted by cat id and the helper's draw indexes THAT list, so every peer names the same cat whatever order its own lists are in. False (the
// caller then runs the original) outside a room or when the vector does not read as cats.
bool unlocks_event_subject(void* vec, void* stream, void* pick, void** out);
// The game is writing an int save property (T_PropSetInt; `name` = the std::string it passes, `value` = what it stores). Inside an event window the value becomes what the property reads as.
void unlocks_property_set(const void* name, int value);

// The level picker (T_LevelPick), before (picked = false: in a room the shared stream is set from the node's seed -- the battle id without a node)
// and after (`out` = the std::string holding the picked level's name): both peers log the stream and the pick.
void unlocks_level_pick(void* kind, void* node, void* out, bool picked);

} // namespace mgmp
